### PR TITLE
Elden carpool creation

### PR DESCRIPTION
**Pull request by eldenyap48**
Hi, I made this into a modal, and added it into the /create_carpool route. I can integrate it into one of the pages later

Screenshot 2023-11-16 at 2 34 31 PM
Screenshot 2023-11-16 at 2 34 27 PM

### CODE REVIEW

**Comment by DylanHuynh** [comment]
@eldenyap48 looks like theres some conflicts to resolve in the package files first. you should probably git pull to see the conflicts I think

**Comment by eldenyap48** [comment]
ok i've git pulled and pushed it to this branch

**Comment by DylanHuynh** [comment]
image
Can you update this field with a label (also don't think you need the image there since there's no other images on the form) thanks

**Comment by eldenyap48** [comment]
ok I've changed it. Should be working perfectly now


Screenshot 2023-11-17 at 7 21 15 PM
Screenshot 2023-11-17 at 7 21 18 PM

**Pull request merged**
